Updated completion files
- Added `get-model-name` command to `nbfc` completion
- Updated FISH completions for FISH version 4.0.0
- Fixed typo in description of `ec_probe watch`

diff --git a/completion/fish/nbfc.fish.in b/completion/fish/nbfc.fish.in
--- a/completion/fish/nbfc.fish.in
+++ b/completion/fish/nbfc.fish.in
@@ -11,6 +11,7 @@ function _nbfc__command
     config 'List or apply configs' \
     set 'Control fan speed' \
     wait-for-hwmon 'Wait for /sys/class/hwmon/hwmon* files' \
+    get-model-name 'Print model name for notebook' \
     help 'Show help'
 end
 
@@ -38,8 +39,11 @@ function _nbfc_fish_query
   #     Checks if the positional argument number NUM is one of WORDS.
   #     NUM counts from one.
   #
-  #   has_option <OPTIONS...>
+  #   has_option [WITH_INCOMPLETE] <OPTIONS...>
   #     Checks if an option given in OPTIONS is passed on commandline.
+  #     If an option requires an argument, this command returns true only if the
+  #     option includes an argument. If 'WITH_INCOMPLETE' is specified, it also
+  #     returns true for options missing their arguments.
   #
   #   option_is <OPTIONS...> -- <VALUES...>
   #     Checks if any option in OPTIONS has a value of VALUES.
@@ -54,20 +58,9 @@ function _nbfc_fish_query
   #
   # ===========================================================================
 
-  set -l func '__fish_query'
-
   set -l positionals
   set -l having_options
   set -l option_values
-
-  switch (count $argv)
-    case 0
-      echo "$func: missing OPTIONS argument" >&2
-      return 1
-    case 1
-      echo "$func: missing COMMAND" >&2
-      return 1
-  end
 
   set -l options $argv[1]
   set -e argv[1]
@@ -87,38 +80,30 @@ function _nbfc_fish_query
     # =========================================================================
 
     set -l short_opts_with_arg
-    set -l long_opts_with_arg
-    set -l old_opts_with_arg
-
     set -l short_opts_without_arg
-    set -l long_opts_without_arg
-    set -l old_opts_without_arg
-
     set -l short_opts_with_optional_arg
+    set -l long_opts_with_arg
+    set -l long_opts_without_arg
     set -l long_opts_with_optional_arg
-    set -l old_opts_with_optional_arg
 
     set -l option
 
     if test -n "$options"
       for option in (string split -- ',' $options)
-        # Using one big switch case is the fastest way
-        switch $option
-          case '--?*=';   set -a long_opts_with_arg           (string replace -- '='  '' $option)
-          case '--?*=\?'; set -a long_opts_with_optional_arg  (string replace -- '=?' '' $option)
-          case '--?*';    set -a long_opts_without_arg        $option
-
-          case '-?=';     set -a short_opts_with_arg          (string replace -- '='  '' $option)
-          case '-?=\?';   set -a short_opts_with_optional_arg (string replace -- '=?' '' $option)
-          case '-?';      set -a short_opts_with_arg          $option
-
-          case '-??*=';   set -a old_opts_with_arg            (string replace -- '='  '' $option)
-          case '-??*=\?'; set -a old_opts_with_optional_arg   (string replace -- '=?' '' $option)
-          case '-??*';    set -a old_opts_without_arg         $option
-
-          case '*'
-            echo "$func: argv[1]: '$option' is not a short, long or old-style option" >&2
-            return 1
+        if false
+          true
+        else if string match -qr -- '^--.+=$' $option
+          set -a long_opts_with_arg (string replace -- '='  '' $option)
+        else if string match -qr -- '^--.+=\?$' $option
+          set -a long_opts_with_optional_arg (string replace -- '=?' '' $option)
+        else if string match -qr -- '^--.+$' $option
+          set -a long_opts_without_arg $option
+        else if string match -qr -- '^-.=$' $option
+          set -a short_opts_with_arg (string replace -- '='  '' $option)
+        else if string match -qr -- '^-.=\?$' $option
+          set -a short_opts_with_optional_arg (string replace -- '=?' '' $option)
+        else if string match -qr -- '^-.$' $option
+          set -a short_opts_without_arg $option
         end
       end
     end
@@ -161,26 +146,6 @@ function _nbfc_fish_query
         case '-*'
           set -l end_of_parsing false
 
-          if string match -q -- "*=*" $arg
-            set -l split (string split -m 1 -- '=' $arg)
-            if contains -- $split[1] $old_opts_with_arg $old_opts_with_optional_arg
-              set -a having_options $split[1]
-              set -a option_values "$split[2]"
-              set end_of_parsing true
-            end
-          else if contains -- $arg $old_opts_with_arg
-            set end_of_parsing true
-            if $have_trailing_arg
-              set -a having_options $arg
-              set -a option_values $cmdline[(math $argi + 1)]
-              set argi (math $argi + 1)
-            end
-          else if contains -- $arg $old_opts_without_arg $old_opts_with_optional_arg
-            set -a having_options $arg
-            set -a option_values ""
-            set end_of_parsing true
-          end
-
           set -l arg_length (string length -- $arg)
           set -l i 2
           while not $end_of_parsing; and test $i -le $arg_length
@@ -202,8 +167,8 @@ function _nbfc_fish_query
                 set argi (math $argi + 1)
               end
             else if contains -- $option $short_opts_with_optional_arg
-              set -a having_options $option
               set end_of_parsing true
+              set -a having_options $option
               set -a option_values "$trailing_chars" # may be empty
             end
 
@@ -229,7 +194,7 @@ function _nbfc_fish_query
   switch $cmd
     case 'positional_contains'
       if test (count $argv) -eq 0
-        echo "$func: positional_contains: argv[3]: missing number" >&2
+        echo "_nbfc_fish_query: positional_contains: argv[3]: missing number" >&2
         return 1
       end
 
@@ -247,54 +212,19 @@ function _nbfc_fish_query
         case 0
           count $positionals
         case 1
-          echo "$func: num_of_positionals: $argv[1]: missing operand" >&2
+          echo "_nbfc_fish_query: num_of_positionals: $argv[1]: missing operand" >&2
           return 1
         case 2
           if contains -- $argv[1] -lt -le -eq -ne -gt -ge;
             test (count $positionals) $argv[1] $argv[2] && return 0 || return 1
           else
-            echo "$func: num_of_positionals: $argv[1]: unknown operator" >&2
+            echo "_nbfc_fish_query: num_of_positionals: $argv[1]: unknown operator" >&2
             return 1
           end
         case '*'
-          echo "$func: num_of_positionals: too many arguments" >&2
+          echo "_nbfc_fish_query: num_of_positionals: too many arguments" >&2
           return 1
       end
-    case 'option_is'
-      set -l options
-      set -l values
-
-      for arg in $argv
-        set -e argv[1]
-
-        if string match -q -- -- $arg
-          set values $argv
-          break
-        else
-          set -a options $arg
-        end
-      end
-
-      if test (count $values) -eq 0
-        echo "$func: missing values" >&2
-        return 1
-      end
-
-      set -l i (count $having_options)
-      while test $i -ge 1
-        if contains -- $having_options[$i] $options
-          if contains -- $option_values[$i] $values
-            return 0
-          end
-        end
-
-        set i (math $i - 1)
-      end
-
-      return 1
-    case '*'
-      echo "$func: argv[2]: invalid command" >&2
-      return 1
   end
 end
 
@@ -348,6 +278,9 @@ end
 set -l prog "nbfc"
 set -l query "_nbfc_fish_query"
 
+# Delete existing completions
+complete -c $prog -e
+
 # Generally disable file completion
 complete -c $prog -x
 
@@ -381,7 +314,7 @@ set -l C002 "$query '$opts' positional_contains 1 status && not $query '$opts' h
 set -l C003 "$query '$opts' positional_contains 1 status && not $query '$opts' has_option -w --watch"
 complete -c $prog -n $C000 -s a -l all -d 'Show service and fan status (default)' -f
 complete -c $prog -n $C001 -s s -l service -d 'Show service status' -f
-complete -c $prog -n $C002 -s f -l fan -d 'Show status of fan (zero based)' -x
+complete -c $prog -n $C002 -s f -l fan -d 'Show status of fan (zero based)' -x -a '(nbfc complete-fans)'
 complete -c $prog -n $C003 -s w -l watch -d 'Show status periodically' -x
 
 # command nbfc config
@@ -405,6 +338,9 @@ complete -c $prog -n $C001 -s s -l speed -d 'Set fan speed to PERCENT' -x
 complete -c $prog -n $C002 -s f -l fan -d 'Fan index (zero based)' -x -a '(nbfc complete-fans)'
 
 # command nbfc wait-for-hwmon
+set -l opts "-h,--help,--version"
+
+# command nbfc get-model-name
 set -l opts "-h,--help,--version"
 
 # command nbfc help
diff --git a/completion/zsh/_ec_probe.in b/completion/zsh/_ec_probe.in
--- a/completion/zsh/_ec_probe.in
+++ b/completion/zsh/_ec_probe.in
@@ -10,7 +10,7 @@ _ec_probe_zsh_query() {
   # This function is for querying the command line.
   #
   # COMMANDS
-  #   setup <OPTIONS> <ARGS...>
+  #   init <OPTIONS> <ARGS...>
   #     This is the first call you have to make, otherwise the other commands
   #     won't (successfully) work.
   #
@@ -27,15 +27,18 @@ _ec_probe_zsh_query() {
   #   get_positional <NUM>
   #     Prints out the positional argument number NUM (starting from 1)
   #
-  #   has_option <OPTIONS...>
+  #   has_option [WITH_INCOMPLETE] <OPTIONS...>
   #     Checks if an option given in OPTIONS is passed on commandline.
+  #     If an option requires an argument, this command returns true only if the
+  #     option includes an argument. If 'WITH_INCOMPLETE' is specified, it also
+  #     returns true for options missing their arguments.
   #
   #   option_is <OPTIONS...> -- <VALUES...>
   #     Checks if one option in OPTIONS has a value of VALUES.
   #
   # EXAMPLE
   #   local POSITIONALS HAVING_OPTIONS OPTION_VALUES
-  #   zsh_query setup '-f,-a=,-optional=?' program_name -f -optional -a foo bar
+  #   zsh_query init '-f,-a=,-optional=?' program_name -f -optional -a foo bar
   #   zsh_query has_option -f
   #   zsh_query option_is -a -- foo
   #
@@ -46,8 +49,6 @@ _ec_probe_zsh_query() {
   #
   # ===========================================================================
 
-  local FUNC="zsh_query"
-
   __zsh_query_contains() {
     local arg='' key="$1"; shift
     for arg; do [[ "$key" == "$arg" ]] && return 0; done
@@ -55,7 +56,7 @@ _ec_probe_zsh_query() {
   }
 
   if [[ $# == 0 ]]; then
-    echo "$FUNC: missing command" >&2
+    echo "_ec_probe_zsh_query: missing command" >&2
     return 1;
   fi
 
@@ -65,12 +66,12 @@ _ec_probe_zsh_query() {
   case "$cmd" in
     get_positional)
       if test $# -ne 1; then
-        echo "$FUNC: get_positional: takes exactly one argument" >&2
+        echo "_ec_probe_zsh_query: get_positional: takes exactly one argument" >&2
         return 1;
       fi
 
       if test "$1" -eq 0; then
-        echo "$FUNC: get_positional: positionals start at 1, not 0!" >&2
+        echo "_ec_probe_zsh_query: get_positional: positionals start at 1, not 0!" >&2
         return 1
       fi
 
@@ -79,7 +80,7 @@ _ec_probe_zsh_query() {
       ;;
     has_option)
       if test $# -eq 0; then
-        echo "$FUNC: has_option: arguments required" >&2
+        echo "_ec_probe_zsh_query: has_option: arguments required" >&2
         return 1;
       fi
 
@@ -107,12 +108,12 @@ _ec_probe_zsh_query() {
       done
 
       if test ${#cmd_option_is_options[@]} -eq 0; then
-        echo "$FUNC: option_is: missing options" >&2
+        echo "_ec_probe_zsh_query: option_is: missing options" >&2
         return 1
       fi
 
       if test ${#cmd_option_is_values[@]} -eq 0; then
-        echo "$FUNC: option_is: missing values" >&2
+        echo "_ec_probe_zsh_query: option_is: missing values" >&2
         return 1
       fi
 
@@ -129,25 +130,24 @@ _ec_probe_zsh_query() {
 
       return 1
       ;;
-    setup)
+    init)
       local IFS=','
       local -a options=(${=1})
       unset IFS
       shift
       ;;
     *)
-      echo "$FUNC: argv[1]: invalid command" >&2
+      echo "_ec_probe_zsh_query: argv[1]: invalid command" >&2
       return 1
       ;;
   esac
 
-  # continuing setup....
+  # continuing init...
 
   # ===========================================================================
   # Parsing of available options
   # ===========================================================================
 
-  local -a   old_opts_with_arg=()   old_opts_with_optional_arg=()   old_opts_without_arg=()
   local -a  long_opts_with_arg=()  long_opts_with_optional_arg=()  long_opts_without_arg=()
   local -a short_opts_with_arg=() short_opts_with_optional_arg=() short_opts_without_arg=()
 
@@ -157,16 +157,10 @@ _ec_probe_zsh_query() {
       --?*=)    long_opts_with_arg+=("${option%=}");;
       --?*=\?)  long_opts_with_optional_arg+=("${option%=?}");;
       --?*)     long_opts_without_arg+=("$option");;
-
       -?=)      short_opts_with_arg+=("${option%=}");;
       -?=\?)    short_opts_with_optional_arg+=("${option%=?}");;
       -?)       short_opts_without_arg+=("$option");;
-
-      -??*=)    old_opts_with_arg+=("${option%=}");;
-      -??*=\?)  old_opts_with_optional_arg+=("${option%=?}");;
-      -??*)     old_opts_without_arg+=("$option");;
-
-      *) echo "$FUNC: $option: not a valid short, long or oldstyle option" >&2; return 1;;
+      *) echo "_ec_probe_zsh_query: $option: not a valid short, long or oldstyle option" >&2; return 1;;
     esac
   done
 
@@ -177,6 +171,7 @@ _ec_probe_zsh_query() {
   POSITIONALS=()
   HAVING_OPTIONS=()
   OPTION_VALUES=()
+  INCOMPLETE_OPTION=''
 
   local argi=2 # argi[1] is program name
   while [[ $argi -le $# ]]; do
@@ -204,30 +199,10 @@ _ec_probe_zsh_query() {
         else
           HAVING_OPTIONS+=("$arg")
           OPTION_VALUES+=("")
-        fi;;
+        fi
+        ;;
       -*)
         local end_of_parsing=false
-
-        if [[ "$arg" == *=* ]]; then
-          local option="${arg%%=*}"
-          local value="${arg#*=}"
-          if __zsh_query_contains "$option" "${old_opts_with_arg[@]}" "${old_opts_with_optional_arg[@]}"; then
-            HAVING_OPTIONS+=("$option")
-            OPTION_VALUES+=("$value")
-            end_of_parsing=true
-          fi
-        elif __zsh_query_contains "$arg" "${old_opts_with_arg[@]}"; then
-          end_of_parsing=true
-          if $have_trailing_arg; then
-            HAVING_OPTIONS+=("$arg")
-            OPTION_VALUES+=("${@[$((argi + 1))]}")
-            (( argi++ ))
-          fi
-        elif __zsh_query_contains "$arg" "${old_opts_without_arg[@]}" "${old_opts_with_optional_arg[@]}"; then
-          HAVING_OPTIONS+=("$arg")
-          OPTION_VALUES+=("")
-          end_of_parsing=true
-        fi
 
         local arg_length=${#arg}
         local i=1
@@ -244,7 +219,7 @@ _ec_probe_zsh_query() {
             if [[ -n "$trailing_chars" ]]; then
               HAVING_OPTIONS+=("$option")
               OPTION_VALUES+=("$trailing_chars")
-            else if $have_trailing_arg
+            elif $have_trailing_arg; then
               HAVING_OPTIONS+=("$option")
               OPTION_VALUES+=("${@[$((argi + 1))]}")
               (( argi++ ))
@@ -256,7 +231,8 @@ _ec_probe_zsh_query() {
           fi
 
           (( i++ ))
-        done;;
+        done
+        ;;
       *)
         POSITIONALS+=("$arg");;
     esac
@@ -272,7 +248,7 @@ _ec_probe__command() {
     read:'Read a byte from a EC register'
     write:'Write a byte to a EC register'
     monitor:'Monitor all EC registers for changes'
-    watch:'Monitor all EC registers for changes (alternative version'
+    watch:'Monitor all EC registers for changes (alternative version)'
   )
 
   _describe -- command items
@@ -280,8 +256,8 @@ _ec_probe__command() {
 
 _ec_probe() {
   local opts=-h,--help,-e=,--embedded-controller=
-  local -a HAVING_OPTIONS=() OPTION_VALUES=() POSITIONALS=()
-  _ec_probe_zsh_query setup "$opts" "${words[@]}"
+  local HAVING_OPTIONS=() OPTION_VALUES=() POSITIONALS=() INCOMPLETE_OPTION=''
+  _ec_probe_zsh_query init "$opts" "${words[@]}"
 
   case "$(_ec_probe_zsh_query get_positional 1)" in
     (dump) _ec_probe_dump; return $?;;
@@ -312,7 +288,7 @@ _ec_probe_dump() {
 _ec_probe_load() {
   local -a args=(
     1:command1:_ec_probe__command
-    2:' ':_files
+    2:FILE:_files
   )
   _arguments -S -s -w "${args[@]}"
 }
@@ -331,15 +307,15 @@ _ec_probe_write() {
     '(--word -w)'{-w,--word}'[Combine two registers into one]'
     1:command1:_ec_probe__command
     2:'Register destination':'({0..255})'
-    3:'Value to write':' '
+    3:'Value to write':_numbers
   )
   _arguments -S -s -w "${args[@]}"
 }
 
 _ec_probe_monitor() {
   local -a args=(
-    '(--interval -i)'{-i+,--interval=}'[Monitored timespan]':seconds:' '
-    '(--timespan -t)'{-t+,--timespan=}'[Set poll intervall]':seconds:' '
+    '(--interval -i)'{-i+,--interval=}'[Monitored timespan]':seconds:"_numbers -f"
+    '(--timespan -t)'{-t+,--timespan=}'[Set poll intervall]':seconds:_numbers
     '(--report -r)'{-r+,--report=}'[Save all readings as a CSV file]':report:_files
     '(--clearly -c)'{-c,--clearly}'[Blanks out consecutive duplicate readings]'
     '(--decimal -d)'{-d,--decimal}'[Output readings in decimal format instead of hexadecimal format]'
@@ -350,8 +326,8 @@ _ec_probe_monitor() {
 
 _ec_probe_watch() {
   local -a args=(
-    '(--interval -i)'{-i+,--interval=}'[Sets the update interval in seconds]':seconds:' '
-    '(--timespan -t)'{-t+,--timespan=}'[Sets how many seconds the program will run]':seconds:' '
+    '(--interval -i)'{-i+,--interval=}'[Sets the update interval in seconds]':seconds:"_numbers -f"
+    '(--timespan -t)'{-t+,--timespan=}'[Sets how many seconds the program will run]':seconds:_numbers
     1:command1:_ec_probe__command
   )
   _arguments -S -s -w "${args[@]}"
