Updated completions

diff --git a/completion/fish/nbfc_service.fish.in b/completion/fish/nbfc_service.fish.in
--- a/completion/fish/nbfc_service.fish.in
+++ b/completion/fish/nbfc_service.fish.in
@@ -1,22 +1,22 @@
-# This script was generated by argparse-shell-complete.
-# argparse-shell-complete: A tool that creates robust and reliable autocompletion scripts using Python's argparse module.
-# For more information, visit: https://github.com/argparse-shell-complete/argparse-shell-complete
+# This script was generated by crazy-complete.
+# crazy-complete: A tool that creates robust and reliable autocompletion scripts for Bash, Fish and Zsh.
+# For more information, visit: https://github.com/crazy-complete/crazy-complete
 
-function _nbfc_service_fish_helper
+function _nbfc_service_fish_query
   # ===========================================================================
   #
   # This function implements the parsing of options and positionals in the Fish shell.
   #
-  # Usage: __fish_helper <OPTIONS> <COMMAND> [ARGS...]
+  # Usage: __fish_query <OPTIONS> <COMMAND> [ARGS...]
   #
-  # The first argument is a comma-seperated list of options that the parser should know about.
+  # The first argument is a comma-separated list of options that the parser should know about.
   # Short options (-o), long options (--option), and old-style options (-option) are supported.
   #
   # If an option takes an argument, it is suffixed by '='.
   # If an option takes an optional argument, it is suffixed by '=?'.
   #
   # For example:
-  #   __fish_helper '-f,--flag,-old-style,--with-arg=,--with-optional=?'
+  #   __fish_query '-f,--flag,-old-style,--with-arg=,--with-optional=?' [...]
   #
   #   Here, -f, --flag and -old-style don't take options, --with-arg requires an
   #   argument and --with-optional takes an optional argument.
@@ -27,7 +27,10 @@ function _nbfc_service_fish_helper
   #     NUM counts from one.
   #
   #   has_option <OPTIONS...>
-  #     Checks if a option given in OPTIONS is passed on commandline.
+  #     Checks if an option given in OPTIONS is passed on commandline.
+  #
+  #   option_is <OPTIONS...> -- <VALUES...>
+  #     Checks if any option in OPTIONS has a value of VALUES.
   #
   #   num_of_positionals [<OPERATOR> <NUMBER>]
   #     Checks the number of positional arguments.
@@ -39,175 +42,177 @@ function _nbfc_service_fish_helper
   #
   # ===========================================================================
 
-  set -l func '__fish_helper'
-
-  set -l short_opts_with_arg
-  set -l long_opts_with_arg
-  set -l old_opts_with_arg
-
-  set -l short_opts_without_arg
-  set -l long_opts_without_arg
-  set -l old_opts_without_arg
-
-  set -l short_opts_with_optional_arg
-  set -l long_opts_with_optional_arg
-  set -l old_opts_with_optional_arg
-
-  set -l option
-
-  # ===========================================================================
-  # Parsing of OPTIONS argument
-  # ===========================================================================
-
-  if test (count $argv) -lt 1
-    echo "$func: missing OPTIONS argument" >&2
-    return 1
-  end
-
-  if test -n "$argv[1]"
-    for option in (string split -- ',' $argv[1])
-      # Using one big switch case is the fastest way
-      switch $option
-        case '--?*=';   set -a long_opts_with_arg           (string replace -- '='  '' $option)
-        case '--?*=\?'; set -a long_opts_with_optional_arg  (string replace -- '=?' '' $option)
-        case '--?*';    set -a long_opts_without_arg        $option
-
-        case '-?=';     set -a short_opts_with_arg          (string replace -- '='  '' $option)
-        case '-?=\?';   set -a short_opts_with_optional_arg (string replace -- '=?' '' $option)
-        case '-?';      set -a short_opts_with_arg          $option
-
-        case '-??*=';   set -a old_opts_with_arg            (string replace -- '='  '' $option)
-        case '-??*=\?'; set -a old_opts_with_optional_arg   (string replace -- '=?' '' $option)
-        case '-??*';    set -a old_opts_without_arg         $option
-
-        case '*'
-          echo "$func: argv[1]: '$option' is not a short, long or old-style option" >&2
-          return 1
-      end
-    end
-  end
-
-  set -e argv[1]
-
-  # ===========================================================================
-  # Parsing of options and positionals
-  # ===========================================================================
+  set -l func '__fish_query'
 
   set -l positionals
   set -l having_options
+  set -l option_values
 
-  set -l cmdline (commandline -poc)
-  set -l cmdline_count (count $cmdline)
+  switch (count $argv)
+    case 0
+      echo "$func: missing OPTIONS argument" >&2
+      return 1
+    case 1
+      echo "$func: missing COMMAND" >&2
+      return 1
+  end
 
-  set -l argi 2 # cmdline[1] is command name
-  while test $argi -le $cmdline_count
-    set -l arg "$cmdline[$argi]"
-    set -l have_trailing_arg (test $argi -lt $cmdline_count && echo true || echo false)
+  set -l options $argv[1]
+  set -e argv[1]
 
-    switch $arg
-      case '-'
-        set -a positionals -
-      case '--'
-        for argi in (seq (math $argi + 1) $cmdline_count)
-          set -a positionals $cmdline[$argi]
+  set -l cmd $argv[1]
+  set -e argv[1]
+
+  set -l my_cache_key "$(commandline -b) $options"
+
+  if test "$__QUERY_CACHE_KEY" = "$my_cache_key"
+    set positionals    $__QUERY_CACHE_POSITIONALS
+    set having_options $__QUERY_CACHE_HAVING_OPTIONS
+    set option_values  $__QUERY_CACHE_OPTION_VALUES
+  else
+    # =========================================================================
+    # Parsing of OPTIONS argument
+    # =========================================================================
+
+    set -l short_opts_with_arg
+    set -l long_opts_with_arg
+    set -l old_opts_with_arg
+
+    set -l short_opts_without_arg
+    set -l long_opts_without_arg
+    set -l old_opts_without_arg
+
+    set -l short_opts_with_optional_arg
+    set -l long_opts_with_optional_arg
+    set -l old_opts_with_optional_arg
+
+    set -l option
+
+    if test -n "$options"
+      for option in (string split -- ',' $options)
+        # Using one big switch case is the fastest way
+        switch $option
+          case '--?*=';   set -a long_opts_with_arg           (string replace -- '='  '' $option)
+          case '--?*=\?'; set -a long_opts_with_optional_arg  (string replace -- '=?' '' $option)
+          case '--?*';    set -a long_opts_without_arg        $option
+
+          case '-?=';     set -a short_opts_with_arg          (string replace -- '='  '' $option)
+          case '-?=\?';   set -a short_opts_with_optional_arg (string replace -- '=?' '' $option)
+          case '-?';      set -a short_opts_with_arg          $option
+
+          case '-??*=';   set -a old_opts_with_arg            (string replace -- '='  '' $option)
+          case '-??*=\?'; set -a old_opts_with_optional_arg   (string replace -- '=?' '' $option)
+          case '-??*';    set -a old_opts_without_arg         $option
+
+          case '*'
+            echo "$func: argv[1]: '$option' is not a short, long or old-style option" >&2
+            return 1
         end
-        break
-      case '--*'
-        for option in $long_opts_with_arg $long_opts_without_arg $long_opts_with_optional_arg
-          if string match -q -- "$option=*" $arg
-            set -a having_options $option
-            break
-          else if string match -q -- $option $arg
-            if contains -- $option $long_opts_with_arg
-              if $have_trailing_arg
-                set -a having_options $option
-                set argi (math $argi + 1)
-              end
-            else
-              set -a having_options $option
-            end
-            break
+      end
+    end
+
+    # =========================================================================
+    # Parsing of options and positionals
+    # =========================================================================
+
+    set -l cmdline (commandline -poc)
+    set -l cmdline_count (count $cmdline)
+
+    set -l argi 2 # cmdline[1] is command name
+    while test $argi -le $cmdline_count
+      set -l arg "$cmdline[$argi]"
+      set -l have_trailing_arg (test $argi -lt $cmdline_count && echo true || echo false)
+
+      switch $arg
+        case '-'
+          set -a positionals -
+        case '--'
+          for argi in (seq (math $argi + 1) $cmdline_count)
+            set -a positionals $cmdline[$argi]
           end
-        end
-      case '-*'
-        set -l have_match false
-
-        for option in $old_opts_with_arg $old_opts_without_arg $old_opts_with_optional_arg
-          if string match -q -- "$option=*" $arg
-            set -a having_options $option
-            set have_match true
-            break
-          else if string match -q -- $option $arg
-            if contains -- $option $old_opts_with_arg
-              if $have_trailing_arg
-                set -a having_options $option
-                set argi (math $argi + 1)
-              end
-            else
-              set -a having_options $option
+          break
+        case '--*=*'
+          set -l split (string split -m 1 -- '=' $arg)
+          set -a having_options $split[1]
+          set -a option_values "$split[2]"
+        case '--*'
+          if contains -- $arg $long_opts_with_arg
+            if $have_trailing_arg
+              set -a having_options $arg
+              set -a option_values $cmdline[(math $argi + 1)]
+              set argi (math $argi + 1)
             end
-
-            set have_match true
-            break
+          else
+            set -a having_options $arg
+            set -a option_values ""
           end
-        end
+        case '-*'
+          set -l end_of_parsing false
 
-        if not $have_match
+          if string match -q -- "*=*" $arg
+            set -l split (string split -m 1 -- '=' $arg)
+            if contains -- $split[1] $old_opts_with_arg $old_opts_with_optional_arg
+              set -a having_options $split[1]
+              set -a option_values "$split[2]"
+              set end_of_parsing true
+            end
+          else if contains -- $arg $old_opts_with_arg
+            set end_of_parsing true
+            if $have_trailing_arg
+              set -a having_options $arg
+              set -a option_values $cmdline[(math $argi + 1)]
+              set argi (math $argi + 1)
+            end
+          else if contains -- $arg $old_opts_without_arg $old_opts_with_optional_arg
+            set -a having_options $arg
+            set -a option_values ""
+            set end_of_parsing true
+          end
+
           set -l arg_length (string length -- $arg)
           set -l i 2
-          set is_end false
-          while not $is_end && test $i -le $arg_length
-            set -l char (string sub -s $i -l 1 -- "$arg")
-            set -l have_trailing_chars (test $i -lt $arg_length && echo true || echo false)
+          while not $end_of_parsing; and test $i -le $arg_length
+            set -l option "-$(string sub -s $i -l 1 -- $arg)"
+            set -l trailing_chars "$(string sub -s (math $i + 1) -- $arg)"
 
-            for option in $short_opts_with_arg $short_opts_without_arg $short_opts_with_optional_arg
-              set -l option_char (string sub -s 2 -l 1 -- $option)
+            if contains -- $option $short_opts_without_arg
+              set -a having_options $option
+              set -a option_values ""
+            else if contains -- $option $short_opts_with_arg
+              set end_of_parsing true
 
-              if test "$char" = "$option_char"
-                if contains -- $option $short_opts_with_arg
-                  if $have_trailing_chars
-                    set -a having_options $option
-                    set is_end true
-                  else if $have_trailing_arg
-                    set -a having_options $option
-                    set argi (math $argi + 1)
-                    set is_end true
-                  end
-                else if contains -- $option $short_opts_with_optional_arg
-                  set -a having_options $option
-
-                  if $have_trailing_chars
-                    set is_end true
-                  end
-                else
-                  set -a having_options $option
-                end
-
-                break
+              if test -n "$trailing_chars"
+                set -a having_options $option
+                set -a option_values $trailing_chars
+              else if $have_trailing_arg
+                set -a having_options $option
+                set -a option_values $cmdline[(math $argi + 1)]
+                set argi (math $argi + 1)
               end
+            else if contains -- $option $short_opts_with_optional_arg
+              set -a having_options $option
+              set end_of_parsing true
+              set -a option_values "$trailing_chars" # may be empty
             end
 
             set i (math $i + 1)
           end
-        end
-      case '*'
-        set -a positionals $arg
+        case '*'
+          set -a positionals $arg
+      end
+
+      set argi (math $argi + 1)
     end
 
-    set argi (math $argi + 1)
+    set -g __QUERY_CACHE_POSITIONALS    $positionals
+    set -g __QUERY_CACHE_HAVING_OPTIONS $having_options
+    set -g __QUERY_CACHE_OPTION_VALUES  $option_values
+    set -g __QUERY_CACHE_KEY            $my_cache_key
   end
 
   # ===========================================================================
   # Commands
   # ===========================================================================
-
-  if test (count $argv) -eq 0
-    echo "$func: missing command" >&2
-    return 1
-  end
-
-  set -l cmd "$argv[1]"
-  set -e argv[1]
 
   switch $cmd
     case 'positional_contains'
@@ -226,19 +231,55 @@ function _nbfc_service_fish_helper
 
       return 1
     case 'num_of_positionals'
-      if test (count $argv) -eq 0
-        count $positionals
-      else if test (count $argv) -eq 2
-        if contains -- $argv[1] -lt -le -eq -ne -gt -ge;
-          test (count $positionals) $argv[1] $argv[2] && return 0 || return 1
-        else
-          echo "$func: num_of_positionals: $argv[1]: unknown operator" >&2
+      switch (count $argv)
+        case 0
+          count $positionals
+        case 1
+          echo "$func: num_of_positionals: $argv[1]: missing operand" >&2
           return 1
+        case 2
+          if contains -- $argv[1] -lt -le -eq -ne -gt -ge;
+            test (count $positionals) $argv[1] $argv[2] && return 0 || return 1
+          else
+            echo "$func: num_of_positionals: $argv[1]: unknown operator" >&2
+            return 1
+          end
+        case '*'
+          echo "$func: num_of_positionals: too many arguments" >&2
+          return 1
+      end
+    case 'option_is'
+      set -l options
+      set -l values
+
+      for arg in $argv
+        set -e argv[1]
+
+        if string match -q -- -- $arg
+          set values $argv
+          break
+        else
+          set -a options $arg
         end
-      else if test (count $argv) -eq 1
-        echo "$func: num_of_positionals: $argv[1]: missing operand" >&2
+      end
+
+      if test (count $values) -eq 0
+        echo "$func: missing values" >&2
         return 1
       end
+
+      set -l i (count $having_options)
+      while test $i -ge 1
+        if contains -- $having_options[$i] $options
+          if contains -- $option_values[$i] $values
+            return 0
+          end
+        end
+
+        set i (math $i - 1)
+      end
+
+      return 1
     case '*'
       echo "$func: argv[2]: invalid command" >&2
       return 1
@@ -246,21 +287,24 @@ function _nbfc_service_fish_helper
 end
 
 set -l prog "nbfc_service"
-set -l helper "_nbfc_service_fish_helper"
+set -l query "_nbfc_service_fish_query"
+
+# Generally disable file completion
+complete -c $prog -x
 
 # command nbfc_service
-set -l options "--help,-h,-r,--read-only,-f,--fork,-d,--debug,-c=,--config-file=,-e=,--embedded-controller="
-set -l guard000 "not $helper '$options' has_option --help -h"
-set -l guard001 "not $helper '$options' has_option -r --read-only"
-set -l guard002 "not $helper '$options' has_option -f --fork"
-set -l guard003 "not $helper '$options' has_option -d --debug"
-set -l guard004 "not $helper '$options' has_option -c --config-file"
-set -l guard005 "not $helper '$options' has_option -e --embedded-controller"
-complete -c $prog -n $guard000 -s h -l help -d 'show this help message and exit' -f
-complete -c $prog -n $guard001 -s r -l read-only -d 'Start in read-only mode' -f
-complete -c $prog -n $guard002 -s f -l fork -d 'Switch process to background after sucessfully started' -f
-complete -c $prog -n $guard003 -s d -l debug -d 'Enable tracing of reads and writes of the embedded controller' -f
-complete -c $prog -n $guard004 -s c -l config-file -d 'Use alternative config file (default @SYSCONFDIR@/nbfc/nbfc.json)' -r -F
-complete -c $prog -n $guard005 -s e -l embedded-controller -d 'Specify embedded controller to use' -x -a 'dummy dev_port ec_sys acpi_ec'
+set -l opts "-h,--help,-r,--read-only,-f,--fork,-d,--debug,-c=,--config-file=,-e=,--embedded-controller="
+set -l C000 "not $query '$opts' has_option -h --help"
+set -l C001 "not $query '$opts' has_option -r --read-only"
+set -l C002 "not $query '$opts' has_option -f --fork"
+set -l C003 "not $query '$opts' has_option -d --debug"
+set -l C004 "not $query '$opts' has_option -c --config-file"
+set -l C005 "not $query '$opts' has_option -e --embedded-controller"
+complete -c $prog -n $C000 -s h -l help -d 'show this help message and exit' -f
+complete -c $prog -n $C001 -s r -l read-only -d 'Start in read-only mode' -f
+complete -c $prog -n $C002 -s f -l fork -d 'Switch process to background after sucessfully started' -f
+complete -c $prog -n $C003 -s d -l debug -d 'Enable tracing of reads and writes of the embedded controller' -f
+complete -c $prog -n $C004 -s c -l config-file -d 'Use alternative config file (default @SYSCONFDIR@/nbfc/nbfc.json)' -rF
+complete -c $prog -n $C005 -s e -l embedded-controller -d 'Specify embedded controller to use' -x -a 'dummy dev_port ec_sys acpi_ec'
 
 # vim: ft=fish ts=2 sts=2 sw=2 et
diff --git a/completion/zsh/_nbfc.in b/completion/zsh/_nbfc.in
--- a/completion/zsh/_nbfc.in
+++ b/completion/zsh/_nbfc.in
@@ -1,159 +1,272 @@
 #compdef nbfc
 
-# This script was generated by argparse-shell-complete.
-# argparse-shell-complete: A tool that creates robust and reliable autocompletion scripts using Python's argparse module.
-# For more information, visit: https://github.com/argparse-shell-complete/argparse-shell-complete
+# This script was generated by crazy-complete.
+# crazy-complete: A tool that creates robust and reliable autocompletion scripts for Bash, Fish and Zsh.
+# For more information, visit: https://github.com/crazy-complete/crazy-complete
 
-_nbfc_get_positional() {
-  local FUNC='get_positional'
-  local CONTAINS="${FUNC}_contains"
+_nbfc_zsh_query() {
+  # ===========================================================================
+  #
+  # This function is for querying the command line.
+  #
+  # COMMANDS
+  #   setup <OPTIONS> <ARGS...>
+  #     This is the first call you have to make, otherwise the other commands
+  #     won't (successfully) work.
+  #
+  #     It parses <ARGS> according to <OPTIONS> and stores results in the
+  #     variables POSITIONALS, HAVING_OPTIONS and OPTION_VALUES.
+  #
+  #     The first argument is a comma-separated list of options that the parser
+  #     should know about. Short options (-o), long options (--option), and
+  #     old-style options (-option) are supported.
+  #
+  #     If an option takes an argument, it is suffixed by '='.
+  #     If an option takes an optional argument, it is suffixed by '=?'.
+  #
+  #   get_positional <NUM>
+  #     Prints out the positional argument number NUM (starting from 1)
+  #
+  #   has_option <OPTIONS...>
+  #     Checks if an option given in OPTIONS is passed on commandline.
+  #
+  #   option_is <OPTIONS...> -- <VALUES...>
+  #     Checks if one option in OPTIONS has a value of VALUES.
+  #
+  # EXAMPLE
+  #   local POSITIONALS HAVING_OPTIONS OPTION_VALUES
+  #   zsh_query setup '-f,-a=,-optional=?' program_name -f -optional -a foo bar
+  #   zsh_query has_option -f
+  #   zsh_query option_is -a -- foo
+  #
+  #   Here, -f is a flag, -a takes an argument, and -optional takes an optional
+  #   argument.
+  #
+  #   Both queries return true.
+  #
+  # ===========================================================================
 
-  $CONTAINS() {
-  local ARG KEY="$1"; shift
-  for ARG; do [[ "$KEY" == "$ARG" ]] && return 0; done
-  return 1
+  local FUNC="zsh_query"
+
+  __zsh_query_contains() {
+    local arg='' key="$1"; shift
+    for arg; do [[ "$key" == "$arg" ]] && return 0; done
+    return 1
   }
 
-  local IFS=','
-  local -a OPTIONS=(${=1})
-  local WANTED_POSITIONAL=$2
-  unset IFS
-  shift 2
-
-  local -a   OLD_OPTS_WITH_ARG   OLD_OPTS_WITH_OPTIONAL_ARG   OLD_OPTS_WITHOUT_ARG
-  local -a  LONG_OPTS_WITH_ARG  LONG_OPTS_WITH_OPTIONAL_ARG  LONG_OPTS_WITHOUT_ARG
-  local -a SHORT_OPTS_WITH_ARG SHORT_OPTS_WITH_OPTIONAL_ARG SHORT_OPTS_WITHOUT_ARG
-
-  local OPTION
-  for OPTION in "${OPTIONS[@]}"; do
-  case "$OPTION" in
-    (--?*=)    LONG_OPTS_WITH_ARG+=("${OPTION//=/}");;
-    (--?*=\?)  LONG_OPTS_WITH_OPTIONAL_ARG+=("${OPTION//=?/}");;
-    (--?*);    LONG_OPTS_WITHOUT_ARG+=("$OPTION");;
-
-    (-?=)      SHORT_OPTS_WITH_ARG+=("${OPTION//=/}");;
-    (-?=\?)    SHORT_OPTS_WITH_OPTIONAL_ARG+=("${OPTION//=?/}");;
-    (-?)       SHORT_OPTS_WITHOUT_ARG+=("$OPTION");;
-
-    (-??*=)    OLD_OPTS_WITH_ARG+=("${OPTION//=/}");;
-    (-??*=\?)  OLD_OPTS_WITH_OPTIONAL_ARG+=("${OPTION//=?/}");;
-    (-??*)     OLD_OPTS_WITHOUT_ARG+=("$OPTION");;
-
-    (*) echo "$FUNC: $OPTION: not a valid short, long or oldstyle option" >&2; return 1;;
-  esac
-  done
-
-  local -a POSITIONALS
-  local -a HAVING_OPTIONS
-
-  local ARGI=2 # ARG[1] is program name
-  while [[ $ARGI -le $# ]]; do
-  local ARG="${@[$ARGI]}"
-  local HAVE_TRAILING_ARG=$(test $ARGI -lt $# && echo true || echo false)
-
-  case "$ARG" in
-    (-)
-      POSITIONALS+=(-);;
-    (--)
-      for ARGI in $(seq $((ARGI + 1)) $#); do
-        POSITIONALS+=("${@[$ARGI]}")
-      done
-      break;;
-    (--*)
-      for OPTION in $LONG_OPTS_WITH_ARG $LONG_OPTS_WITHOUT_ARG $LONG_OPTS_WITH_OPTIONAL_ARG; do
-        if [[ "$ARG" == "$OPTION="* ]]; then
-          HAVING_OPTIONS+=("$OPTION")
-          break
-        elif [[ "$ARG" == "$OPTION" ]]; then
-          if $CONTAINS "$OPTION" "${LONG_OPTS_WITH_ARG[@]}"; then
-            if $HAVE_TRAILING_ARG; then
-              HAVING_OPTIONS+=("$OPTION")
-              (( ARGI++ ))
-            fi
-          else
-            HAVING_OPTIONS+=("$OPTION")
-          fi
-          break
-        fi
-      done;;
-    (-*)
-      local HAVE_MATCH=false
-
-      for OPTION in $OLD_OPTS_WITH_ARG $OLD_OPTS_WITHOUT_ARG $OLD_OPTS_WITH_OPTIONAL_ARG; do
-        if [[ "$ARG" == "$OPTION="* ]]; then
-          HAVING_OPTIONS+=("$OPTION")
-          HAVE_MATCH=true
-          break
-        elif [[ "$ARG" == "$OPTION" ]]; then
-          if $CONTAINS "$OPTION" "${OLD_OPTS_WITH_ARG[@]}"; then
-            if $HAVE_TRAILING_ARG; then
-              HAVING_OPTIONS+=("$OPTION")
-              (( ARGI++ ))
-            fi
-          else
-            HAVING_OPTIONS+=("$OPTION")
-          fi
-
-          HAVE_MATCH=true
-          break
-        fi
-      done
-
-      if ! $HAVE_MATCH; then
-        local ARG_LENGTH=${#ARG}
-        local I=1
-        local IS_END=false
-        while ! $IS_END && test $I -lt $ARG_LENGTH; do
-          local ARG_CHAR="${ARG:$I:1}"
-          local HAVE_TRAILING_CHARS=$(test $((I+1)) -lt $ARG_LENGTH && echo true || echo false)
-
-          for OPTION in $SHORT_OPTS_WITH_ARG $SHORT_OPTS_WITHOUT_ARG $SHORT_OPTS_WITH_OPTIONAL_ARG; do
-            local OPTION_CHAR="${OPTION:1:1}"
-
-            if test "$ARG_CHAR" = "$OPTION_CHAR"; then
-              if $CONTAINS "$OPTION" "${SHORT_OPTS_WITH_ARG[@]}"; then
-                if $HAVE_TRAILING_CHARS; then
-                  HAVING_OPTIONS+=("$OPTION")
-                  IS_END=true
-                elif $HAVE_TRAILING_ARG; then
-                  HAVING_OPTIONS+=("$OPTION")
-                  (( ARGI++ ))
-                  IS_END=true
-                fi
-              elif $CONTAINS "$OPTION" "${SHORT_OPTS_WITH_OPTIONAL_ARG[@]}"; then
-                HAVING_OPTIONS+=("$OPTION")
-
-                if $HAVE_TRAILING_CHARS; then
-                  IS_END=true
-                fi
-              else
-                HAVING_OPTIONS+=("$OPTION")
-              fi
-
-              break
-            fi
-          done
-
-          (( I++ ))
-        done
-      fi;;
-    (*)
-      POSITIONALS+=("$ARG");;
-  esac
-
-  (( ARGI++ ))
-  done
-
-  if test $WANTED_POSITIONAL -eq 0; then
-  echo "$FUNC: argv[2]: positionals start at 1, not 0!" >&2
-  return 1
+  if [[ $# == 0 ]]; then
+    echo "$FUNC: missing command" >&2
+    return 1;
   fi
 
-  printf "%s" "${POSITIONALS[$WANTED_POSITIONAL]}"
+  local cmd="$1"
+  shift
+
+  case "$cmd" in
+    get_positional)
+      if test $# -ne 1; then
+        echo "$FUNC: get_positional: takes exactly one argument" >&2
+        return 1;
+      fi
+
+      if test "$1" -eq 0; then
+        echo "$FUNC: get_positional: positionals start at 1, not 0!" >&2
+        return 1
+      fi
+
+      printf "%s" "${POSITIONALS[$1]}"
+      return 0
+      ;;
+    has_option)
+      if test $# -eq 0; then
+        echo "$FUNC: has_option: arguments required" >&2
+        return 1;
+      fi
+
+      local option=''
+      for option in "${HAVING_OPTIONS[@]}"; do
+        __zsh_query_contains "$option" "$@" && return 0
+      done
+
+      return 1
+      ;;
+    option_is)
+      local -a cmd_option_is_options cmd_option_is_values
+      local end_of_options_num=0
+
+      while test $# -ge 1; do
+        if [[ "$1" == "--" ]]; then
+          (( ++end_of_options_num ))
+        elif test $end_of_options_num -eq 0; then
+          cmd_option_is_options+=("$1")
+        elif test $end_of_options_num -eq 1; then
+          cmd_option_is_values+=("$1")
+        fi
+
+        shift
+      done
+
+      if test ${#cmd_option_is_options[@]} -eq 0; then
+        echo "$FUNC: option_is: missing options" >&2
+        return 1
+      fi
+
+      if test ${#cmd_option_is_values[@]} -eq 0; then
+        echo "$FUNC: option_is: missing values" >&2
+        return 1
+      fi
+
+      local I=${#HAVING_OPTIONS[@]}
+      while test $I -ge 1; do
+        local option="${HAVING_OPTIONS[$I]}"
+        if __zsh_query_contains "$option" "${cmd_option_is_options[@]}"; then
+          local VALUE="${OPTION_VALUES[$I]}"
+          __zsh_query_contains "$VALUE" "${cmd_option_is_values[@]}" && return 0
+        fi
+
+        (( --I ))
+      done
+
+      return 1
+      ;;
+    setup)
+      local IFS=','
+      local -a options=(${=1})
+      unset IFS
+      shift
+      ;;
+    *)
+      echo "$FUNC: argv[1]: invalid command" >&2
+      return 1
+      ;;
+  esac
+
+  # continuing setup....
+
+  # ===========================================================================
+  # Parsing of available options
+  # ===========================================================================
+
+  local -a   old_opts_with_arg=()   old_opts_with_optional_arg=()   old_opts_without_arg=()
+  local -a  long_opts_with_arg=()  long_opts_with_optional_arg=()  long_opts_without_arg=()
+  local -a short_opts_with_arg=() short_opts_with_optional_arg=() short_opts_without_arg=()
+
+  local option=''
+  for option in "${options[@]}"; do
+    case "$option" in
+      --?*=)    long_opts_with_arg+=("${option%=}");;
+      --?*=\?)  long_opts_with_optional_arg+=("${option%=?}");;
+      --?*)     long_opts_without_arg+=("$option");;
+
+      -?=)      short_opts_with_arg+=("${option%=}");;
+      -?=\?)    short_opts_with_optional_arg+=("${option%=?}");;
+      -?)       short_opts_without_arg+=("$option");;
+
+      -??*=)    old_opts_with_arg+=("${option%=}");;
+      -??*=\?)  old_opts_with_optional_arg+=("${option%=?}");;
+      -??*)     old_opts_without_arg+=("$option");;
+
+      *) echo "$FUNC: $option: not a valid short, long or oldstyle option" >&2; return 1;;
+    esac
+  done
+
+  # ===========================================================================
+  # Parsing of command line options
+  # ===========================================================================
+
+  POSITIONALS=()
+  HAVING_OPTIONS=()
+  OPTION_VALUES=()
+
+  local argi=2 # argi[1] is program name
+  while [[ $argi -le $# ]]; do
+    local arg="${@[$argi]}"
+    local have_trailing_arg=$(test $argi -lt $# && echo true || echo false)
+
+    case "$arg" in
+      -)
+        POSITIONALS+=(-);;
+      --)
+        for argi in $(seq $((argi + 1)) $#); do
+          POSITIONALS+=("${@[$argi]}")
+        done
+        break;;
+      --*=*)
+        HAVING_OPTIONS+=("${arg%%=*}")
+        OPTION_VALUES+=("${arg#*=}");;
+      --*)
+        if __zsh_query_contains "$arg" "${long_opts_with_arg[@]}"; then
+          if $have_trailing_arg; then
+            HAVING_OPTIONS+=("$arg")
+            OPTION_VALUES+=("${@[$((argi + 1))]}")
+            (( argi++ ))
+          fi
+        else
+          HAVING_OPTIONS+=("$arg")
+          OPTION_VALUES+=("")
+        fi;;
+      -*)
+        local end_of_parsing=false
+
+        if [[ "$arg" == *=* ]]; then
+          local option="${arg%%=*}"
+          local value="${arg#*=}"
+          if __zsh_query_contains "$option" "${old_opts_with_arg[@]}" "${old_opts_with_optional_arg[@]}"; then
+            HAVING_OPTIONS+=("$option")
+            OPTION_VALUES+=("$value")
+            end_of_parsing=true
+          fi
+        elif __zsh_query_contains "$arg" "${old_opts_with_arg[@]}"; then
+          end_of_parsing=true
+          if $have_trailing_arg; then
+            HAVING_OPTIONS+=("$arg")
+            OPTION_VALUES+=("${@[$((argi + 1))]}")
+            (( argi++ ))
+          fi
+        elif __zsh_query_contains "$arg" "${old_opts_without_arg[@]}" "${old_opts_with_optional_arg[@]}"; then
+          HAVING_OPTIONS+=("$arg")
+          OPTION_VALUES+=("")
+          end_of_parsing=true
+        fi
+
+        local arg_length=${#arg}
+        local i=1
+        while ! $end_of_parsing && test $i -lt $arg_length; do
+          local option="-${arg:$i:1}"
+          local trailing_chars="${arg:$((i+1))}"
+
+          if __zsh_query_contains "$option" "${short_opts_without_arg[@]}"; then
+            HAVING_OPTIONS+=("$option")
+            OPTION_VALUES+=("")
+          elif __zsh_query_contains "$option" "${short_opts_with_arg[@]}"; then
+            end_of_parsing=true
+
+            if [[ -n "$trailing_chars" ]]; then
+              HAVING_OPTIONS+=("$option")
+              OPTION_VALUES+=("$trailing_chars")
+            else if $have_trailing_arg
+              HAVING_OPTIONS+=("$option")
+              OPTION_VALUES+=("${@[$((argi + 1))]}")
+              (( argi++ ))
+            fi
+          elif __zsh_query_contains "$option" "${short_opts_with_optional_arg[@]}"; then
+            end_of_parsing=true
+            HAVING_OPTIONS+=("$option")
+            OPTION_VALUES+=("$trailing_chars") # may be empty
+          fi
+
+          (( i++ ))
+        done;;
+      *)
+        POSITIONALS+=("$arg");;
+    esac
+
+    (( argi++ ))
+  done
 }
 
-_nbfc_command() {
-  local -a DESCRIBE=(
+_nbfc__command() {
+  local -a items=(
     start:'Start the service'
     stop:'Stop the service'
     restart:'Restart the service'
@@ -164,30 +277,27 @@ _nbfc_command() {
     help:'Show help'
   )
 
-  _describe -- command DESCRIBE
+  _describe -- command items
 }
 
 _nbfc_exec() {
-  local IFS=$'\n'
-  local -a OUTPUT_LINES=($(eval "$1"))
-  unset IFS
+  local -a describe=()
+  local item='' desc=''
 
-  local -a DESCRIBE
-  local LINE
+  while IFS=$'\t' read -r item desc; do
+    item="${item/:/\\:/}"
+    describe+=("$item:$desc")
+  done < <(eval "$1")
 
-  for LINE in "${OUTPUT_LINES[@]}"; do
-  LINE="${LINE/:/\\:/}"
-  LINE="${LINE/$'\t'/:}"
-  DESCRIBE+=("$LINE")
-  done
-
-  _describe '' DESCRIBE
+  _describe '' describe
 }
 
 _nbfc() {
-  # We have to check for subcommands here, because _arguments modifies $words
-  local opts="--help,-h,--version"
-  case "$(_nbfc_get_positional "$opts" 1 "${words[@]}")" in
+  local opts=-h,--help,--version
+  local -a HAVING_OPTIONS=() OPTION_VALUES=() POSITIONALS=()
+  _nbfc_zsh_query setup "$opts" "${words[@]}"
+
+  case "$(_nbfc_zsh_query get_positional 1)" in
     (start) _nbfc_start; return $?;;
     (stop) _nbfc_stop; return $?;;
     (restart) _nbfc_restart; return $?;;
@@ -198,98 +308,81 @@ _nbfc() {
     (help) _nbfc_help; return $?;;
   esac
 
-  local -a arguments=(
-    '(--help -h)'{--help,-h}'[show this help message and exit]'::' '
-    --version"[show program's version number and exit]"::' '
-    1:command1:_nbfc_command
+  local -a args=(
+    '(--help -h)'{-h,--help}'[show this help message and exit]'
+    '(--version)'--version"[show program's version number and exit]"
+    1:command1:_nbfc__command
   )
-
-  _arguments -S "${arguments[@]}"
+  _arguments -S -s -w "${args[@]}"
 }
 
 _nbfc_start() {
-  local -a arguments=(
-    '(--help -h)'{--help,-h}'[show this help message and exit]'::' '
-    '(--read-only -r)'{--read-only,-r}'[Start in read-only mode]'::' '
-    1:command1:_nbfc_command
+  local -a args=(
+    '(--read-only -r)'{-r,--read-only}'[Start in read-only mode]'
+    1:command1:_nbfc__command
   )
-
-  _arguments -S "${arguments[@]}"
+  _arguments -S -s -w "${args[@]}"
 }
 
 _nbfc_stop() {
-  local -a arguments=(
-    '(--help -h)'{--help,-h}'[show this help message and exit]'::' '
-    1:command1:_nbfc_command
+  local -a args=(
+    1:command1:_nbfc__command
   )
-
-  _arguments -S "${arguments[@]}"
+  _arguments -S -s -w "${args[@]}"
 }
 
 _nbfc_restart() {
-  local -a arguments=(
-    '(--help -h)'{--help,-h}'[show this help message and exit]'::' '
-    '(--read-only -r)'{--read-only,-r}'[Restart in read-only mode]'::' '
-    1:command1:_nbfc_command
+  local -a args=(
+    '(--read-only -r)'{-r,--read-only}'[Restart in read-only mode]'
+    1:command1:_nbfc__command
   )
-
-  _arguments -S "${arguments[@]}"
+  _arguments -S -s -w "${args[@]}"
 }
 
 _nbfc_status() {
-  local -a arguments=(
-    '(--help -h)'{--help,-h}'[show this help message and exit]'::' '
-    '(--fan --service -f -s --all -a)'{--all,-a}'[Show service and fan status (default)]'::' '
-    '(--all --fan -a -f --service -s)'{--service,-s}'[Show service status]'::' '
-    '(--all --service -a -s --fan -f)'{--fan=,-f+}'[Show status of fan (zero based)]':'FAN INDEX':' '
-    '(--watch -w)'{--watch=,-w+}'[Show status periodically]':SECONDS:' '
-    1:command1:_nbfc_command
+  local -a args=(
+    '(--fan --service -f -s --all -a)'{-a,--all}'[Show service and fan status (default)]'
+    '(--all --fan -a -f --service -s)'{-s,--service}'[Show service status]'
+    '(--all --service -a -s --fan -f)'{-f+,--fan=}'[Show status of fan (zero based)]':'FAN INDEX':' '
+    '(--watch -w)'{-w+,--watch=}'[Show status periodically]':SECONDS:' '
+    1:command1:_nbfc__command
   )
-
-  _arguments -S "${arguments[@]}"
+  _arguments -S -s -w "${args[@]}"
 }
 
 _nbfc_config() {
-  local -a arguments=(
-    '(--help -h)'{--help,-h}'[show this help message and exit]'::' '
-    '(--apply --recommend --set -a -r -s --list -l)'{--list,-l}'[List all available configs (default)]'::' '
-    '(--apply --list --recommend -a -l -r --set -s)'{--set=,-s+}'[Set a config]':config:"_files -W @DATADIR@/nbfc/configs"
-    '(--list --recommend --set -l -r -s --apply -a)'{--apply=,-a+}'[Set a config and enable fan control]':config:"_files -W @DATADIR@/nbfc/configs"
-    '(--apply --list --set -a -l -s --recommend -r)'{--recommend,-r}'[List configs which may work for your device]'::' '
-    1:command1:_nbfc_command
+  local -a args=(
+    '(--apply --recommend --set -a -r -s --list -l)'{-l,--list}'[List all available configs (default)]'
+    '(--apply --list --recommend -a -l -r --set -s)'{-s+,--set=}'[Set a config]':config:"_files -W @DATADIR@/nbfc/configs"
+    '(--list --recommend --set -l -r -s --apply -a)'{-a+,--apply=}'[Set a config and enable fan control]':config:"_files -W @DATADIR@/nbfc/configs"
+    '(--apply --list --set -a -l -s --recommend -r)'{-r,--recommend}'[List configs which may work for your device]'
+    1:command1:_nbfc__command
   )
-
-  _arguments -S "${arguments[@]}"
+  _arguments -S -s -w "${args[@]}"
 }
 
 _nbfc_set() {
-  local -a arguments=(
-    '(--help -h)'{--help,-h}'[show this help message and exit]'::' '
-    '(--speed -s --auto -a)'{--auto,-a}"[Set fan speed to 'auto']"::' '
-    '(--auto -a --speed -s)'{--speed=,-s+}'[Set fan speed to PERCENT]':PERCENT:' '
-    '(--fan -f)'{--fan=,-f+}'[Fan index (zero based)]':'FAN INDEX':"{_nbfc_exec 'nbfc complete-fans'}"
-    1:command1:_nbfc_command
+  local -a args=(
+    '(--speed -s --auto -a)'{-a,--auto}"[Set fan speed to 'auto']"
+    '(--auto -a --speed -s)'{-s+,--speed=}'[Set fan speed to PERCENT]':PERCENT:' '
+    '(--fan -f)'{-f+,--fan=}'[Fan index (zero based)]':'FAN INDEX':"{_nbfc_exec 'nbfc complete-fans'}"
+    1:command1:_nbfc__command
   )
-
-  _arguments -S "${arguments[@]}"
+  _arguments -S -s -w "${args[@]}"
 }
 
 _nbfc_wait_for_hwmon() {
-  local -a arguments=(
-    '(--help -h)'{--help,-h}'[show this help message and exit]'::' '
-    1:command1:_nbfc_command
+  local -a args=(
+    1:command1:_nbfc__command
   )
-
-  _arguments -S "${arguments[@]}"
+  _arguments -S -s -w "${args[@]}"
 }
 
 _nbfc_help() {
-  local -a arguments=(
-    '(--help -h)'{--help,-h}'[show this help message and exit]'::' '
-    1:command1:_nbfc_command
+  local -a args=(
+    1:command1:_nbfc__command
   )
-
-  _arguments -S "${arguments[@]}"
+  _arguments -S -s -w "${args[@]}"
 }
 
 _nbfc "$@"
